#!/usr/bin/env ruby
# Run this from inside the dotfiles dir
Dir.glob(".[a-z]*").each do |file_name|
  unless ['.git', '.gitignore'].include? file_name
    rm = `rm -rf ~/#{file_name}`
    ln = `ln -s ~/Projects/dotfiles/#{file_name} ~/`
  end
end
