#!/usr/bin/env bash

# default values = hottest project!
rvm="1.8.7"
project_dir="$HOME/Projects/tracks/tracks"

case `echo $1 | tr "[A-Z]" "[a-z]"` in
cnz|creativenz)
 rvm="1.9.2"
 project_dir="$HOME/Projects/creativenz/creativenz"
 ;;
invoicer)
 rvm="1.8.7"
 project_dir="$HOME/Projects/invoicer/invoicer"
 ;;
tracks)
 rvm="1.8.7"
 project_dir="$HOME/Projects/tracks/tracks"
 ;;
labour|etrac)
 rvm="1.8.7"
 project_dir="$HOME/Projects/labour/labour/trunk/Labour"
 ;;
power|powerswitch)
 rvm="1.8.7"
 project_dir="$HOME/Projects/consumer/consumer/branches/development/powerswitch/Consumer"
 ;;
learningconnexion|phoenix)
 rvm="1.8.7"
 project_dir="$HOME/Projects/Learning-Connexion/Learning-Connexion"
 ;;
dot|dotfiles)
 rvm="default"
 project_dir="$HOME/Projects/dotfiles/dotfiles"
 ;;
esac

rvm $rvm
cd $project_dir

