#!/usr/bin/env bash

# Shortcuts to my various projects. Yes the name is long and clunky, I usually alias it to 'p'

project_base_dir="$HOME/Projects"

personal="$project_base_dir"
three_months="$project_base_dir/3months"

default_project_dir="$three_months/consumer/mahout/consumer"

case `echo $1 | tr "[A-Z]" "[a-z]"` in
# ---
# Personal Projects
# ---
blueandwhite|blue|bw)
  project_dir="$personal/blueandwhite/blueandwhite"
  ;;
cheekymonkey|cheeky|monkey|cm)
  project_dir="$personal/cheekymonkey/cheekymonkey.co.nz"
  ;;
dot|dotfiles)
  project_dir="$personal/dotfiles"
  ;;
hungryfamilyfeedit|hffi|recipe)
  project_dir="$personal/hungryfamilyfeedit/hungryfamilyfeedit"
  ;;
invoicer)
  project_dir="$personal/invoicer/invoicer"
  ;;
mysportsresults|msr)
  project_dir="$personal/mysportsresults/mysportsresults"
  ;;
tracks)
  project_dir="$personal/tracks/tracks"
  ;;
tracks2|t2)
  project_dir="$personal/tracks2/tracks"
  ;;
# ---
# 3months Projects
# ---
skip|tiny|adventures)
  project_dir="$three_months/skip/tiny-adventures"
  ;;
cnz|creativenz)
  project_dir="$three_months/creativenz/creativenz"
  ;;
pharmac)
  project_dir="$three_months/pharmac/pharmac-prototype"
  ;;
psnz)
  project_dir="$three_months/psnz/pharmaceutical-society"
  ;;
bankomb|bomb|banking|bankingombudsman)
  project_dir="$three_months/ombudsman-banking/ombudsman-banking"
  ;;
ombudsman|ombudsmen)
  project_dir="$three_months/ombudsmen/ombudsmen"
  ;;
hpa-infohub|infohub)
  project_dir="$three_months/hpa/health-promotion-agency"
  ;;
hpa-living|living)
  project_dir="$three_months/hpa/hpa-living"
  ;;
healthcare|health)
  project_dir="$three_months/healthcare/Healthcare-NZ"
  ;;
labour|etrac)
  project_dir="$three_months/labour/etrac"
  ;;
sportnz)
  project_dir="$three_months/sportnz/sportnz-assessment-tool"
  ;;
horse|horsepower)
  project_dir="$three_months/horse/horse-power"
  ;;
fcf|first|first-click-free|first_click_free)
  project_dir="$three_months/first-click-free/first_click_free"
  ;;
dev|minutes)
  project_dir="$three_months/dev-meeting-minutes"
  ;;
learningconnexion|phoenix|tlc)
  project_dir="$three_months/tlc/Learning-Connexion"
  ;;
ham|hamilton|hamiltonwaikat|hamiltonwaikato)
  project_dir="$three_months/hamiltonwaikato/hamilton-waikato"
  ;;
stc|stc-shop|save)
  project_dir="$three_months/stc/savethechildren-site"
  ;;
nzags|surgeon|surgeons)
  project_dir="$three_months/nzags/surgeons"
  ;;
# Consumer ---
draft-admin.consumer|consumer_admin|draft-admin|admin)
  project_dir="$three_months/consumer/consumer_admin_draft/ConsumerAdmin"
  ;;
draft.consumer|consumer_public|public)
  project_dir="$three_months/consumer/consumer_public_draft/ConsumerPublic"
  ;;
calculator_draft|calculator|draft-calc|calc)
  project_dir="$three_months/consumer/calculator_draft/PowerswitchCalculator"
  ;;
www-admin.consumer|cpa|admin_production|www-admin|admin_prod)
  project_dir="$three_months/consumer/consumer_admin_production/ConsumerAdmin"
  ;;
consumer_public_production|www.consumer|consumer_production)
  project_dir="$three_months/consumer/consumer_public_production/ConsumerPublic"
  ;;
powerswitch|www.powerswitch|ps)
  project_dir="$three_months/consumer/powerswitch/powerswitch"
  ;;
telme|www.telme)
  project_dir="$three_months/consumer/telme/telme"
  ;;
calc_production|calc_prod|calculator_production|calculator_prod|www-calc|calc_prod)
  project_dir="$three_months/consumer/calculator_production/PowerswitchCalculator"
  ;;
consumer)
  project_dir="$three_months/consumer/mahout/consumer"
  ;;
consumer-knife)
  project_dir="$three_months/consumer/mahout/consumer-knife"
  ;;
*)
  project_dir=$default_project_dir
  ;;
esac

if [ -d $project_dir ]; then
  if [ "$project_dir" == "$default_project_dir" ]; then
    #echo "** default project **"
    echo -e "\033[32m** default project **\033[0m"
  fi
  cd $project_dir
else
  #echo "Cannot find project dir for \"$1\", tried: $project_dir"
  echo -e "\033[31mCannot find project dir for \"$1\", tried: $project_dir\033[0m"
fi

